Symmetrize transforms + more transforms + EquivariantDenoiser
deepinv/deepinv pull request #259
Opened 2024-06-26 09:16 UTC by Andrewwango

- Allow deterministic transform
- Consolidate all transforms to use `get_params` then `transform`
- Symmetrise transform i.e. `T_inv f(Tx)` where T_inv and T are the same realisation
- Add random selection operator: `t = t1 | t2`
- Add full tests for transform arithmetic + all transforms
- Add `figsize` param for `dinv.utils.plot`
- Change equivariant denoiser to accept any transform!
- Reflect transform
- Time-shift transform
- Diffeomorphism transform
- Transform docs now a separate page

Hi @matthieutrs @tachella , do you have any equivariant denoiser examples you could test this new EquivariantDenoiser on?

### Checks to be done before submitting your PR
- [x] `python3 -m pytest tests/` runs successfully.
- [x] `black .` runs successfully.
- [x] `make html` runs successfully (in the `docs/` directory).
- [x] Updated docstrings related to the changes (as applicable).
- [x] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-07-24 15:58 UTC, tachella requested changes
Thanks for the PR! I really like the flexibility of the Transform class.

I think we should move the Transform docs outside Losses, since now it is almost a module on its own.

I am also wondering if `symmetrize` is working properly for `Rotate()` and `Shift()`? The automatic negation wouldn't work right?

Another important point is whether choosing degrees = 4 gives perfect 90 degree rotations (and thus perfect permutation matrices which are invertible) or not. This would save us from doing a specific Rotation90 class.

It would be nice to have `Reflection()` which is another transform that can be used for symmetrizing denoisers.

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        Symmetrize a function for Reynolds Averaging:
```suggestion
        Symmetrize a function by averaging over the group (also known as Reynolds averaging):
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        >>> f = lambda x: x.pow(2) # Function to be symmetrized
This function is already rotoshift symmetric...

what about
```suggestion
        >>> f = lambda x: x[..., 0]*x # Function to be symmetrized
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        E.g. rotation degrees or shift amounts. Override this to implement a custom transform.
Not sure what this means...

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        :return dict: keyword args of transform parameters e.g. {'theta': 30}
```suggestion
        :return dict: keyword args of transform parameters e.g. ``{'theta': 30}``
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +class Param(torch.Tensor):
Can we change this to TransformParam? 

The current name is too generic.

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/rotate.py
> +        :param torch.Tensor, list x_shift: iterable of rotation angles (degrees), one per n_trans.
```suggestion
        :param torch.Tensor, list x_shift: iterable of rotation angles (degrees), one per ``n_trans``.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/scale.py
> +    # def invert_params(self, params: dict) -> dict:
should we remove this commented part?

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/scale.py
> +        :param torch.Tensor, list factor: iterable of scale factors to be used, one per n_trans*batch_size.
```suggestion
        :param torch.Tensor, list factor: iterable of scale factors to be used, one per ``n_trans*batch_size``.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/scale.py
> +        :param torch.Tensor, list center: iterable of scale centers, one per n_trans*batch_size.
```suggestion
        :param torch.Tensor, list center: iterable of scale centers, one per ``n_trans*batch_size``.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/shift.py
> +        :param torch.Tensor, list x_shift: iterable of shifts in x direction, one per n_trans.
```suggestion
        :param torch.Tensor, list x_shift: iterable of shifts in x direction, one per ``n_trans``.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/shift.py
> +        :param torch.Tensor, list y_shift: iterable of shifts in y direction, one per n_trans.
```suggestion
        :param torch.Tensor, list y_shift: iterable of shifts in y direction, one per ``n_trans``.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/utils/plotting.py
> +    :param tuple[int] figsize: size of the figure.
```suggestion
    :param tuple[int] None, figsize: size of the figure.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/utils/plotting.py
> +    :param tuple[int] figsize: size of the figure.
Describe the behaviour if None

2024-07-24 15:58 UTC, tachella commented on docs/source/deepinv.loss.rst
>  Transforms
I think we can move this outside of Loss, ie to a new `deepinv.transform.rst` file

2024-07-24 15:58 UTC, tachella commented on docs/source/deepinv.loss.rst
> +    >>> f = lambda x: x.pow(2) # Function to be symmetrized
```suggestion
    >>> f = lambda x: x[..., 0]*x # Function to be symmetrized
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        def symmetrized(x, *args, **kwargs):
does this work for denoisers which take `x, sigma`?

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +            return self.inverse(
We should add a parameter `n_samples=1` (or similar) which lets you average over a larger number of random monte carlo evaluations

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        Given a function :math:`f(\cdot):X\rightarrow X` and a transform :math:`T_g`, return the function :math:`T_g^{-1} f(T_g \cdot)`
```suggestion
        Given a function :math:`f(\cdot):X\rightarrow X` and a transform :math:`T_g`, returns the group averaged function  :math:`\sum_{i=1}^N T_{g_i}^{-1} f(T_{g_i} \cdot)` where :math:`N` is the number of random transformations.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/base.py
> +        """
add  `n_samples` parameter.

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/rotate.py
> +    Generates n_trans randomly rotated versions of 2D images with zero padding.
```suggestion
    Generates ``n_trans`` randomly rotated versions of 2D images with zero padding.
```

2024-07-24 15:58 UTC, tachella commented on deepinv/transform/rotate.py
>      :param degrees: images are rotated in the range of angles (-degrees, degrees)
It seems to me that this is not what the function is doing, right?

It seems to be sampling from multiples of `360/degrees`?

2024-07-24 16:00 UTC, tachella commented on deepinv/transform/base.py
> +        >>> f = lambda x: x.pow(2) # Function to be symmetrized
I'm also a bit unsure of whether symmetrize would work well with composed transforms like rotoshift?

2024-09-11 09:44 UTC, tachella reviewed
Really great PR! I really like all the new transforms and functionalities.

Besides mostly esthetic suggestions to the docstrings, I've only spotted two issues to address (or at least discuss):
- Rotate 90 degrees * Flip2D is unfortunately a non-abelian group with 8 elements instead of 16. Can we code it up to reduce compute time?
- Symmetrize seems to work in parallel by leveraging more memory - can we add a sequential, less memory intensive option? I'm thinking that over a group of 8 elements, having a x8 memory requirement might be too much to ask.

2024-09-11 09:44 UTC, tachella commented on deepinv/tests/test_transform.py
> +    if "BODMAS" in transform_name:
It might be worth explaining it in a comment, so the tests are more readable.

2024-09-11 09:44 UTC, tachella commented on deepinv/tests/test_transform.py
> +def test_rotate_90():
great!

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/rotate.py
>      :param torch.Generator rng: random number generator, if None, use torch.Generator(), defaults to None
```suggestion
    :param torch.Generator rng: random number generator, if ``None``, use :meth:`torch.Generator`, defaults to ``None``
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
> +    :param bool constant_shape: if True, transformed images are assumed to be same shape as input.
```suggestion
    :param bool constant_shape: if ``True``, transformed images are assumed to be same shape as input.
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
>      :param torch.Generator rng: random number generator, if None, use torch.Generator(), defaults to None
```suggestion
    :param torch.Generator rng: random number generator, if ``None``, use :meth:`torch.Generator`, defaults to ``None``
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
> +    All transforms automatically handle video input (5D of shape (B,C,T,H,W)) by flattening the time dim .
```suggestion
    All transforms automatically handle video input (5D of shape ``(B,C,T,H,W)``) by flattening the time dimension.
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
> +    :param bool flatten_video_input: accept video (5D) input of shape (B,C,T,H,W) by flattening time dim before transforming and unflattening after all operations.
```suggestion
    :param bool flatten_video_input: accept video (5D) input of shape ``(B,C,T,H,W)`` by flattening time dim before transforming and unflattening after all operations.
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
> +        Params are represented as tensors where the first dimension indexes batch and n_trans.
```suggestion
        Params are represented as tensors where the first dimension indexes batch and ``n_trans``.
```

2024-09-11 09:44 UTC, tachella commented on deepinv/transform/base.py
> +                return xt.reshape(-1, *x.shape).mean(axis=0) if average else xt
the current implementation uses |G| extra memory right?
can we add an option that uses |G| extra compute also?

2024-09-11 09:51 UTC, Andrewwango commented on deepinv/models/equivariant.py
> +                self.transform = Rotate(
Good point! Could just make a Dihedral group

2024-09-11 16:15 UTC, tachella approved these changes

2024-09-11 16:15 UTC, merged