Blur 3D and correction/addition to conv2D
deepinv/deepinv pull request #277
Opened 2024-07-12 17:02 UTC by fsarron

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ x ] `black .` runs successfully.
- [  ] `make html` runs successfully (in the `docs/` directory).
- [ x ] Updated docstrings related to the changes (as applicable).
- [ x ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

pytests, doctests and examples related to the new functions passed. Some other unrelated tests and examples are failing.

2024-07-15 10:06 UTC, fsarron commented
Hello @tachella @matthieutrs 

I am finally passing all the tests. I requested for a review from you. 

Note that I had to change the spectral norm test of the "radio" operator. There was a bug in test_physics on the main such that all operators were tested with a bound = 0.2 (`if "space_deblur"` was always `True`) https://github.com/deepinv/deepinv/blob/07da18961041dfb2c6a68d6e3080d37834fe272e/deepinv/tests/test_physics.py#L315-L320

The norm of the "radio" operator is equal to 1.15, so it was no passing the 1e-2 bound. As a quick fox, I added "radio" to the list of operators for which the bound is relaxed. I let you review if this is expected of if the operator should be fixed.

2024-07-18 14:15 UTC, tachella requested changes
The PR looks very good, it is a great contribution!

I have minor comments here and there, mostly of style.

We can discuss tomorrow the points in detail.

2024-07-18 14:15 UTC, tachella commented on deepinv/tests/test_functional.py
> +def test_downsampling_adjointness(device):
I think this should go in test_physics.py

2024-07-18 14:15 UTC, tachella commented on deepinv/tests/test_physics.py
> +    print(error2)
remove print here too

2024-07-26 08:39 UTC, samuro95 commented on examples/patch-priors/demo_epll.py
> +#     torch.cuda.empty_cache()
To remove

2024-08-08 14:35 UTC, fsarron commented on examples/basics/demo_pansharpening.py
> +img_size = (3, 65, 65)
No reason. I probably tested something. I went back to 64.

2024-08-08 15:23 UTC, fsarron commented
@tachella The PR is ready to be merged on my side. I made all the changes you suggested. Pierre did the convolution 2d.

I don't know why GH tells me merging is blocked. Maybe you have more rights to do the merge ? Thanks for your help.

2024-08-08 17:02 UTC, merged