UNSURE loss
deepinv/deepinv pull request #313
Opened 2024-09-29 15:47 UTC by tachella

Adding a small modification to the SURE loss such that it can **optionally** handle unknown noise levels.

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-09-30 07:54 UTC, Andrewwango requested changes
Can we add a `rng` to SURE methods inits and replace `torch.randn_like` and `torch.rand_like` with `torch.empty_like(input).normal_(generator=self.rng)` and `torch.empty_like(input).uniform_(generator=self.rng)`? (similar to `deepinv.physics.noise.NoiseModel`)

2024-10-03 13:12 UTC, tachella commented on deepinv/training/adversarial.py
> +    def setup_train(self, **kwargs):
done

2024-10-03 13:49 UTC, tachella commented on deepinv/physics/blur.py
> +        self.update_parameters(filter, **kwargs)
done

2024-10-03 13:50 UTC, tachella commented on deepinv/physics/noise.py
> +    def update_parameters(self, gain=None, **kwargs):
done

2024-10-10 09:48 UTC, Andrewwango requested changes

2024-10-10 09:48 UTC, Andrewwango commented on deepinv/training/adversarial.py
> +    def setup_train(self, **kwargs):
@tachella have you pushed this change?

2024-10-11 14:40 UTC, tachella commented
@Andrewwango I did push that change

2024-10-11 16:36 UTC, Andrewwango approved these changes

2024-10-11 18:57 UTC, merged