Doc add denoiser tour
deepinv/deepinv pull request #338
Opened 2024-10-29 11:31 UTC by tomMoral

Tour of the denoisers

2025-01-02 20:07 UTC, matthieutrs requested changes
Great PR, thanks a lot and sorry for the late review 😅 

I mainly have two suggestions:
- increase noise levels for clearer visuals and add zooms in the images;
- add a renormalization to adapt fixed noise-level denoisers to the noise level, for fairer comparisons.

Let me know what you think!!

2025-04-18 15:18 UTC, matthieutrs approved these changes
thanks a lot Thomas, looking good to me now, just fixed minor display issues (tight layouts, sizes etc) and will merge when tests pass!

2025-04-21 20:14 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +}
Locally, I had a hard time to run `SwinIR`, so I guess this is why the doc rendering is broken on the CI.

Also, I would rather keep only one plot for this one. I did not include `SCUNet` as visually, I just wanted a comparison with one good denoiser which I chose to be `DRUNet`:
```suggestion
denoiser_results = {
    f"Original": image,
    f"Noisy": noisy_image,
    f"DnCNN": dncnn(noisy_image, sigma),
    f"DnCNN (adapted)": adapted_dncnn(noisy_image, sigma),
    # Skipping SwinIR which does not run on the CI
    # f"SwinIR": swinir(noisy_image, sigma),
    # f"SwinIR (adapted)": adapted_swinir(noisy_image, sigma),
    f"DRUNet": drunet(noisy_image, sigma),
}
```

2025-04-21 20:14 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +noisy_image = image + sigma * torch.randn_like(image)
Why create a new noisy image here?
```suggestion
```

2025-04-21 21:24 UTC, matthieutrs commented on examples/basics/demo_denoiser_tour.py
> +noisy_image = image + sigma * torch.randn_like(image)
because the sigma was cached from before so the denoisers were not used at the right noise level for the visualization - lazy fix on my side

2025-04-21 21:25 UTC, matthieutrs commented on examples/basics/demo_denoiser_tour.py
> +}
thanks, I was struggling to understand why it failed, everything was fine locally on my side!

2025-04-28 09:08 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +    group.plot(x="th", y="psnr", ax=axes[0], color=cmap(norm(sigma)), label=None)
```suggestion
for sig, group in groups:
    group.plot(x="th", y="psnr", ax=axes[0], color=cmap(norm(sig)), label=None)
```

2025-04-28 09:13 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +    for sigma, v in zip(noise_levels, psnr_x)
```suggestion
    {"sigma": sig.item(), "denoiser": "Noisy", "psnr": v.item(), "time": 0.0}
    for sig, v in zip(noise_levels, psnr_x)
```

2025-04-28 09:14 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +            for sigma, v in zip(noise_levels, psnr_x)
```suggestion
            {"sigma": sig.item(), "denoiser": name, "psnr": v.item(), "time": runtime}
            for sig, v in zip(noise_levels, psnr_x)
```

2025-04-28 09:22 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +)
To keep it simple, i would have only one plot, with the new DnCNN and comparison with one denoiser (DRUNet).
```suggestion
# sphinx_gallery_multi_image = "single"
denoiser_results = {
    f"Original": image,
    f"Noisy": noisy_image,
    f"DnCNN": dncnn(noisy_image, sigma),
    f"DnCNN (adapted)": adapted_dncnn(noisy_image, sigma),
    # f"SwinIR": swinir(noisy_image, sigma),
    # f"SwinIR (adapted)": adapted_swinir(noisy_image, sigma),
    f"DRUNet": drunet(noisy_image, sigma),
}
show_image_comparison(
    denoiser_results, ref=image, suptitle=rf"Noise level $\sigma={sigma:.2f}$"
)
```

2025-04-28 09:22 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +            for sigma, v in zip(noise_levels, psnr_x)
```suggestion
            {"sigma": sig.item(), "denoiser": name, "psnr": v.item(), "time": runtime}
            for sig, v in zip(noise_levels, psnr_x)
```

2025-04-28 09:22 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +    ax.set_ylabel("PSNR")
```suggestion
for i, sig in enumerate(noise_levels[[0, 4]]):
    ax = fig.add_subplot(grid[1, i])
    to_plot = merge_df.query(f"sigma == {sig}")
    handles = []
    for name, g in to_plot.groupby("denoiser"):
        handles.append(ax.scatter(g["time"], g["psnr"], label=name))
    ax.set_title(rf"$\sigma={sig:.2f}$")
    ax.set_xscale("log")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("PSNR")
```

2025-04-28 13:08 UTC, tomMoral commented on examples/basics/demo_denoiser_tour.py
> +    # f"SwinIR": swinir(noisy_image, sigma),
```suggestion
    # Skipping SwinIR on CI due to high memory usage
    # f"SwinIR": swinir(noisy_image, sigma),
```

2025-04-29 09:11 UTC, matthieutrs approved these changes

2025-04-29 11:25 UTC, merged

2025-04-29 12:01 UTC, tomMoral commented
:tada: