Add multiscale framework to physics with an example
deepinv/deepinv pull request #342
Opened 2024-10-29 15:08 UTC by Nils-Laurent

Not in a state to be merged yet, but gives visibility on the work. If you have any feedback, do not hesitate.

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-10-29 17:25 UTC, Andrewwango commented
Should the downsample etc. functions be methods of `Physics`? It feels quite specialised, maybe it's better to put them in a separate class e.g. `MultiScaleBase` and when you want to use it you could do

```python
class MultiscaleInpainting(Inpainting, MultiScaleBase):
    pass
```

2024-10-31 11:40 UTC, Andrewwango commented
Marking as draft

2024-11-04 17:50 UTC, tachella commented
> Thank you for this interesting feedback @Andrewwango. I agree that having a separated multiscale framework could allow for more general algorithms, and that multiscale is not necessarily related to `Physics` class (e.g. an upscaling algorithm for handling non-uniform deformation with antialiasing as we discussed).
> 
> Maybe, as a first step, multiscale could be associated with `Physics` (with the currently proposed structure) and adapted later if a more relevant structure becomes easier to spot. I think about this strategy pro/cons as follows:
> 
> * '+' provides tools and interface for handling coarser scale in the context of inverse problems concisely (as shown in the example)
> * '-' will change the interface of physics : if we choose the proposed structure, it means that if we change `Physics` interface later, it might break users code
> 
> I think that if the interface on `Physics` makes sense, then we can accept the proposed structure (because if we implement in a separate class later, we can always use it in Physics afterward). How do you feel about it ? @Andrewwango, @tachella

I think that it makes sense to add it to Physics directly with a NoImplementedError by default, since it doesn't add overhead to the physics class, and doesn't require defining more intermediate classes.

2024-11-06 08:47 UTC, Nils-Laurent commented
@Andrewwango I like this idea. MultiscaleBase would then have multiscale related methods (so Physics would be unchanged) and the downsampling operator would be a member of MultiscaleBase. I have to think about how MultiscaleBase would use fine scale physics methods such as A_dagger (probably by sending "self" to __init__ of MultiscaleBase, which would be member, I will see if this is possible)

2024-11-06 08:58 UTC, tachella commented
> @Nils-Laurent @tachella agreed, it was more a conceptual point whether to_coarse should be that general (esp when lots of physics can't implement it) - just thinking ahead if we have many more functionalities like this it might crowd Physics ("cognitive overhead").
> 
> How about every time we want to let a new physics have multiscale functionality we let it derive from MultiScaleBase too? Eg
> 
> ```
> class Physics:
> ... unchanged 
> 
> class MultiscaleBase:
> ... as above 
> 
> class MRI(DecomposablePhysics):
> ... unchanged 
> 
> class Inpainting(DecompPhysics, MSBase):
> ... 
> ... def to_coarse(...):
> ...
> ```
> 
> This way the user doesn't need to implement their own class (unlike what I initially suggested) but it still separates the multiscale stuff into their own logical class

I think this solution is better, but I still don't agree with the idea that many operators will not be able to implement the multiscale approach. We could potentially provide a default implementation in physics of ``to_coarse`` that returns $A' = AS$ where $S$ is an upsampling operator, and this should work for any operator.

2024-11-06 09:09 UTC, Nils-Laurent commented
@tachella This is a good point. Does that mean that we would target `LinearPhysics` ?

2024-11-08 13:18 UTC, Andrewwango commented
> @tachella This is a good point. ~Does that mean that we would target `LinearPhysics` ?~ Nevermind, I agree it works in the general case

Cool - I didn't realise that there could be a default implementation - in which case that looks good to me. Looking forward to seeing what that would look like.

2024-11-22 16:07 UTC, Nils-Laurent commented
I have changed `Physics ` class to have a general `to_coarse` function.
I am unsure on one point, should there be a `initialize_downsampling_operator` ? (It has one usage in `downsample_signal` but it is mentioned in `to_coarse`, which cannot be used if there is no downsampling operator).

2024-12-11 09:02 UTC, tachella requested changes
Hi Nils,

The PR is looking good, but I have a question/comment regarding how you construct the `to_coarse` operator. We should also add this method with the adjoint for the important case of LinearPhysics.

2024-12-11 09:02 UTC, tachella commented on examples/plug-and-play/demo_PnP_multiscale.py
> +This example describe the usage of multiple scales with Plug-and-Play schemes.
maybe add a more detailed description here

2025-01-01 10:12 UTC, tachella requested changes, later dismissed

2025-01-01 10:12 UTC, tachella commented on examples/plug-and-play/demo_PnP_multiscale.py
> +Multiscale Plug-and-Play
I think we should wait until the paper is on arxiv to upload this example. I would nonetheless start merging the rest

2025-01-01 10:12 UTC, tachella commented on examples/plug-and-play/demo_PnP_multiscale.py
> +max_iter = 200
Can you reduce this a bit? It will be a bit heavy to run every time the docs are built

2025-01-01 10:12 UTC, tachella commented on examples/plug-and-play/demo_PnP_multiscale.py
> +# Multiscale case : use a coarse setting to initialize the fine setting.
Remove space before ":"

2025-01-01 10:12 UTC, tachella commented on examples/plug-and-play/demo_PnP_multiscale.py
> +Multiscale Plug-and-Play
Another option is to only change the initialisation, but then I wouldn't call it multilevel PnP

2025-01-01 17:07 UTC, Nils-Laurent commented on deepinv/physics/blur.py
>  class BlurFFT(DecomposablePhysics):
You are right, I will define the code in a function and use it both for Blur and BlurFFT

2025-01-01 17:09 UTC, Nils-Laurent commented on examples/plug-and-play/demo_PnP_multiscale.py
> +Multiscale Plug-and-Play
Once the rest is ready, we can merge it if that's fine and add the example later

2025-01-01 17:14 UTC, Nils-Laurent commented on examples/plug-and-play/demo_PnP_multiscale.py
> +max_iter = 200
I took it down to 10 iterations which gives a good result

2025-01-01 17:32 UTC, Nils-Laurent commented on deepinv/physics/forward.py
> +        return LinearPhysics(A=A_coarse, A_adjoint=A_coarse_adj)
Good point, I did not check it, and it does not pass the test. I will investigate

2025-02-04 15:37 UTC, tachella commented on deepinv/tests/test_physics.py
> +    if not len(imsize) == 3:
Why are you only testing images with 3 channels?

2025-08-03 16:53 UTC, jscanvic commented
I believe `LinearPhysics.to_coarse` was mistakenly moved to `ComposedPhysics` during the last merge see:

https://github.com/deepinv/deepinv/blob/1e93d35067e8190612f0c0b6119116e7c9346a1b/deepinv/physics/forward.py#L822
https://github.com/deepinv/deepinv/blob/ec54d297e19cd0c134f6be31109df8747e4e5363/deepinv/physics/forward.py#L609

It appears to be what makes the tests fail too. I tried to fix it in 1cda9d1e8e96e1fb5f9c15e69fb76c3b0e751215 feel free to revert if it's not what's intended!

2025-10-31 15:46 UTC, Nils-Laurent commented
I have finally a new version of the PR that I think worth reviewing.
If any of you have time to look at it, thanks!

2026-07-03 22:21 UTC, Tmodrzyk commented
Hi @Nils-Laurent sorry we seem to have missed your update ! The multiscale physics is still very interesting for the lib so I'll try to have a look soon, don't hesitate to ping me or the other reviewers ! :smile:

2026-07-20 07:59 UTC, Nils-Laurent commented
> Hi @Nils-Laurent sorry we seem to have missed your update ! The multiscale physics is still very interesting for the lib so I'll try to have a look soon, don't hesitate to ping me or the other reviewers ! 😄

Hi! That's great, I have time in the incoming weeks to work on it.
I will check the merge conflicts and notify you and other reviewers once its done :)

2026-07-28 21:25 UTC, Nils-Laurent commented
Ok, so I think the PR is fine for being reviewed @tachella, @Tmodrzyk, @jscanvic , @Andrewwango. I will be glad to have your feedback on this work.

The last CI did fail `test_least_squares_implicit_backward[device0-BiCGStab-deblur_valid-2]`. I saw that happen for another PR (e.g. PR1295 Add RNG support to GammaNoise and FisherTippettNoise). Could this test randomly fail for accuracy issues in computations ?

@tachella, I checked the previous change requests, I think they are all either resolved or out of date (do not hesitate if it is not the case).

2026-07-29 09:15 UTC, Tmodrzyk submitted a review, later dismissed
Hi @Nils-Laurent, thank you again for this awesome PR ! 

There are a few high-level issues that should be addressed first:

- we now type basically everything, both in the functions declaration and in the docstring. The `wrappers.py` file lacks typing in several places.

- in the built demo file (you can check it here: https://github.com/deepinv/deepinv/actions/runs/30389846437/artifacts/8701226754) the PnP reconstruction seems barely above no-learning, is this expected ? Also in this cell, there is no explanation with regard to what we should or should not observe in the reconstructions. More explanations would be great. :D
Otherwise the multiscale reconstruction looks great.

- the demo uses the old way of constructing optimization algorithms. See the preferred syntax here https://deepinv.org/auto_examples/basics/demo_custom_optim.html#using-a-predefined-optimization-algorithm

2026-07-29 10:14 UTC, Andrewwango requested changes
super cool @Nils-Laurent and I'm happy to see this continued!

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/optim/data_fidelity.py
> +        The gradient is either computed using the chain rule, or using specific implementation of deepinv.physics.LinearPhysics.A_adjoint_A in the case of a LinearPhysics:
small grammatical issue: surely the equation below refers to the chain rule, but this sentence makes it sound like the equation refers to the linear case. Maybe put the linear case instead below somewhere?

2026-07-29 10:14 UTC, Andrewwango commented on docs/source/api/deepinv.physics.rst
> +   deepinv.physics.BlurMultiScaler
do you need to add these to user guide too?

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +        for factor in factors:
can't we do this more compactly like above with 
```python
        self.Upsamplings = [
            Upsampling(img_size=img_shape, filter=filter if dtype is None else filter.to(dtype=dtype), factor=factor, device=device)
            for factor in factors
        ]

``` ?

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +    This function creates the proper MultiScaler object associated with the provided physics.
since this is the top level function, this should be added to the user guide. Also, add more documentation to this docstring: what is the behaviour? i.e. blur, blurfft and inpainting get special treatment. Why do they need special treatment?

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +        device = physics.device
not all physics have a device attribute - see #968 #989

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +    img_shape: tuple,
we use img_size nomenclature rather than img_shape

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +    This function creates the proper MultiScaler object associated with the provided physics.
also 2D only

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +        Less computationnaly expensive version than parent class :class:`LinearPhysicsMultiScaler`
```suggestion
        Less computationally expensive version than parent class :class:`LinearPhysicsMultiScaler`
```

2026-07-29 10:14 UTC, Andrewwango commented on deepinv/physics/wrappers.py
> +    This function creates the proper MultiScaler object associated with the provided physics.
And if the user wants to speed up their own physics they can write their own wrapper class if the ywant

2026-07-29 13:02 UTC, Nils-Laurent commented on docs/source/api/deepinv.physics.rst
> +   deepinv.physics.BlurMultiScaler
No I agree, I think the top-level function is sufficient.

2026-07-30 14:07 UTC, jscanvic commented
/gpu-tests

2026-07-30 14:15 UTC, jscanvic commented
Thanks for your review @Tmodrzyk @Andrewwango!

I'm helping Nils update the PR to the current standards

- The demo should be clearer, especially that the baseline PnP is expected to perform badly
- It should be clearer what coarser scale physics represent / how they're computed and why specific implementations for linear physics and blur and inpainting are provided
- I also added a virtual method for `downsample_measurement` to make it clearer that it's only implemented for certain operators as there's no easy way to compute it in general

With Nils' changes all points should be covered

@Nils-Laurent Don't hesitate to rewrite some of the stuff I added if it's incorrect / misleading!

2026-07-30 16:46 UTC, Nils-Laurent commented
Thank you all for your valuable feedback @Tmodrzyk, @Andrewwango, @jscanvic ,
and thank you very much @jscanvic for your help!

On my side, I think the PR looks good.

Maybe just a remark about the two multi-scale tests, i.e.
* test_multiscale_coarse_adjointness
* test_multiscale_A_adjoint_A

Their current implementation distinguish between two cases. Either `find_operator` gives sufficiently high resolution, and it is used as it is, otherwise, `find_operator` is called with a specific `imsize` setting the number of channels to `3`. When a new LinearPhysics is implemented, those tests could fail if the intended number of channel should not be set to `3`. Is that fine ?

2026-07-31 10:31 UTC, Andrewwango approved these changes
LGTM

2026-07-31 12:19 UTC, Tmodrzyk reviewed
LGTM, nitpick on the demo

2026-07-31 12:19 UTC, Tmodrzyk commented on examples/plug-and-play/demo_PnP_multiscale.py
> +# a coarse scale corresponding the fine scale downsampled by a factor of 2.
```suggestion
# a coarse scale corresponding to the fine scale downsampled by a factor of 2.
```

2026-07-31 12:19 UTC, Tmodrzyk commented on examples/plug-and-play/demo_PnP_multiscale.py
> +dinv.test(model=model_ms, **test_kwargs)
These plots are awesome ! 
Nit: in the rendered doc, in the first plot the PSNR and residual subplots are slightly overlaping

2026-07-31 12:39 UTC, jscanvic commented on examples/plug-and-play/demo_PnP_multiscale.py
> +# a coarse scale corresponding the fine scale downsampled by a factor of 2.
My bad good catch!

2026-07-31 12:55 UTC, jscanvic commented on examples/plug-and-play/demo_PnP_multiscale.py
> +dinv.test(model=model_ms, **test_kwargs)
It appears it's a bug in `plot_curves` and it's not straightforward to fix - I opened #1308 so it can be fixed in another PR

2026-07-31 12:55 UTC, jscanvic commented
Thank you both! @Tmodrzyk it should be good now

2026-07-31 12:55 UTC, jscanvic commented
/gpu-tests

2026-07-31 15:56 UTC, jscanvic commented
CI failures are unrelated - I'm merging

2026-07-31 15:56 UTC, merged