Ptychography phase retrieval
deepinv/deepinv pull request #351
Opened 2024-11-08 13:46 UTC by vsechaud

Add a new phase retrieval forward operator "Ptychography" with an basics example.

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-11-12 15:42 UTC, zhiyhucode commented
Nice pr! Let me know if you need help regarding the PhaseRetrieval class or any other alignment.

2024-11-14 10:11 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +    :param str probe_type: Type of probe (e.g., "disk"), used if `probe` is not provided.
Currently only supports "disk"?

2024-11-14 10:13 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        :return: Array of (x, y) shifts.
```suggestion
        :return np.ndarray: Array of (x, y) shifts.
```

2024-11-14 10:14 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        :param n_img: Number of shifts (must be a perfect square).
```suggestion
        :param int n_img: Number of shifts (must be a perfect square).
```
The other params `size`, `probe_radius` seem unused?

2024-11-14 10:14 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        :param fov: Field of view for shift computation.
```suggestion
        :param int fov: Field of view for shift computation.
```

2024-11-14 10:16 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        assert int(np.sqrt(n_img)) ** 2 == n_img, "n_img needs to be a perfect square"
I would use `if ...: raise ValueError(...)` instead of assert

2024-11-14 10:17 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        :param x: Input tensor.
typing here please

2024-11-14 10:17 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +        :param probe: Probe tensor.
typing

2024-11-14 10:17 UTC, Andrewwango commented on deepinv/physics/phase_retrieval.py
> +    :param device: Device "cpu" or "gpu".
```suggestion
    :param torch.device, str device: Device "cpu" or "gpu".
```

2024-11-14 10:19 UTC, Andrewwango requested changes
Please see minor aesthetic comments above, thanks Victor! (sorry for all the comments)

2024-12-13 10:54 UTC, tachella commented on docs/source/deepinv.physics.rst
this file should be removed

2024-12-13 10:55 UTC, tachella requested changes
there is an spurious file and the API ref is missing

2024-12-13 10:55 UTC, tachella commented on docs/source/deepinv.physics.rst
also add the operator to docs/api/physics

2024-12-17 15:18 UTC, tachella requested changes
I have a few final corrections

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    :param array_like shifts: shifts of the probe.
be more specific, should the input be a torch.Tensor? 
what is the expected size of the tensor?

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    :param int n_img: Number of shifted probe positions (should be a perfect square).
isn't this redundant with the positions?

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    Forward linear operator for phase retrieval in ptychography. Modelling multiple applications of the shifted probe and Fourier transform on an input image.
```suggestion
    Forward linear operator for phase retrieval in ptychography. 
    
    Models multiple applications of the shifted probe and Fourier transform on an input image.
```

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +        Applies the adjoint operator to `y`.
```suggestion
        Applies the adjoint operator to ``y``.
```

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +        Applies the forward operator to the input image `x` by shifting the probe,
```suggestion
        Applies the forward operator to the input image ``x`` by shifting the probe,
```

2024-12-17 15:18 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    :param str probe_type: Type of probe (e.g., "disk"), used if `probe` is not provided.
```suggestion
    :param str probe_type: Type of probe (e.g., "disk"), used if ``probe`` is not provided.
```

restructured text is different than markdown, you need to use double accents to have code format.

2024-12-17 15:18 UTC, tachella commented
don't forget also to add your contribution to the CHANGELOG file

2024-12-18 07:35 UTC, tachella requested changes
some little corrections on the docstrings.

please also add the new probe and shifts function to the API/User Guide

2024-12-18 07:35 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    :param None,array_like shifts: A 2D array of shape (``n_img``, 2) corresponding to the shifts for the probe. If None, shifts are generated with :func:`deepinv.physics.phase_retrieval.generate_shi
```suggestion
    :param None, torch.Tensor shifts: A 2D array of shape ``(N, 2)`` corresponding to the ``N`` shift positions for the probe. If ``None``, shifts are generated with :func:`deepinv.physics.phase_retrieval.generate_shifts` with ``N=25``.
```

2024-12-18 07:35 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    :param None,torch.Tensor probe: A tensor of shape ``img_size`` representing the probe function. If None, a disk probe is generated with :func:`deepinv.physics.phase_retrieval.build_probe` functio
```suggestion
    :param None, torch.Tensor probe: A tensor of shape ``img_size`` representing the probe function. If ``None``, a disk probe is generated with :func:`deepinv.physics.phase_retrieval.build_probe` with disk shape and radius 10.
```

2024-12-18 07:35 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +    where :math:`F` is the 2D Fourier transform, :math:`P` is the probe function and :math:`T_l` is a shift.
```suggestion
    where :math:`F` is the 2D Fourier transform, :math:`\text{diag}(p)` is associated with the probe :math:`p` and :math:`T_l` is a 2D shift.
```

2024-12-18 07:35 UTC, tachella commented on deepinv/physics/phase_retrieval.py
> +        B_l = F P T_l, \quad l = 1, \dots, n_{\text{img}},
```suggestion
        B_l = F \text{diag}(p) T_l, \quad l = 1, \dots, n_{\text{img}},
```

2024-12-19 10:02 UTC, tachella requested changes
some final fixes

2024-12-19 10:02 UTC, tachella commented on docs/source/user_guide/physics/physics.rst
> +     - | :func:`Build_Probe <deepinv.physics.phase_retrieval.build_probe>`
```suggestion
     - | :func:`build_probe <deepinv.physics.phase_retrieval.build_probe>`
```

2024-12-19 10:02 UTC, tachella commented on docs/source/user_guide/physics/physics.rst
> +       | :func:`Generate_Shifts <deepinv.physics.phase_retrieval.generate_shifts>`
```suggestion
       | :func:`generate_shifts <deepinv.physics.phase_retrieval.generate_shifts>`
```

2024-12-19 10:02 UTC, tachella commented on examples/basics/demo_ptychography.py
> +===================================================
same here with the =======================

2024-12-19 10:51 UTC, tachella approved these changes

2024-12-19 11:37 UTC, merged