Fix DiffUNet diffusion
deepinv/deepinv pull request #360
Opened 2024-11-26 12:16 UTC by matthieutrs

Ongoing work for fixing DiffUNet-based algorithms.

This fixes #359 

TODO:
- [x] fix DiffPIR
- [ ] fix DPS
- [ ] add tests for diffusion quality on toy inpainting problems

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-12-17 09:54 UTC, tachella requested changes
the PR looks good, I just found two details to fix, and also please add the fix to the changelog before merging

2024-12-17 09:54 UTC, tachella commented on examples/sampling/demo_diffpir.py
> +# print(asdasd)
this seems to have slipped

2024-12-17 09:54 UTC, tachella commented on examples/sampling/demo_diffpir.py
> +        denoised = 2 * out - 1
```suggestion
        denoised = 2 * out - 1 # back to [-1, 1]
```

2024-12-17 12:55 UTC, matthieutrs commented on examples/sampling/demo_diffpir.py
> +# print(asdasd)
thanks! done

2024-12-17 12:56 UTC, matthieutrs commented on examples/sampling/demo_diffpir.py
> +        denoised = 2 * out - 1
thanks! done

2024-12-18 16:43 UTC, tachella commented on deepinv/tests/test_sampling.py
> +def test_diffpir_inpaint(device):
merge this test with DPS one using a pytest.parameterize decorator

2024-12-19 10:33 UTC, merged