Draft: CASSI physics
deepinv/deepinv pull request #377
Opened 2024-12-18 20:38 UTC by Andrewwango

CASSI 

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2024-12-19 10:25 UTC, tachella requested changes
I'm wondering if we shouldn't do the shear operation in parallel + see other minor comments on the docs.

2024-12-19 15:28 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +        shifts = (torch.arange(x.shape[1]) * self.shear_factor).floor().int()
done

2024-12-19 15:44 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +    :param str mode: 'sd' = single disperser (i.e. only spatial encoding) or
done

2024-12-19 15:45 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +    :param str shear_dim: shear in H-C plane or W-C plane where C is channel dim, defaults to "h"
done

2024-12-19 15:45 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +            \Sigma_{c=1}^{C} SMx & \text{if mode='sd'}
done

2024-12-19 15:45 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +            \Sigma_{c=1}^{C} S^{-1} MSx & \text{if mode='ss'} \\
done

2024-12-19 15:45 UTC, Andrewwango commented on deepinv/physics/cassi.py
> +    We provide two specific popular CASSI models: Single-Disperser (i.e. only spatial encoding)
done

2025-01-17 13:36 UTC, tachella commented on deepinv/physics/generator/inpainting.py
> -        random_split_ratio: bool = False,
why are you removing these lines?

2025-01-17 13:54 UTC, tachella approved these changes

2025-01-17 13:54 UTC, merged