Docs hyperlinks fixes
deepinv/deepinv pull request #379
Opened 2024-12-20 20:26 UTC by tachella

There are many hyperlinks in the current doc that do not work in the library, mostly due to bad usage of links.

I've added the `nitpicky = True` option to the sphinx configuration file `conf.py` to raise warnings each time there is a broken link in the doc. I found out a huge number of errors which I've fixed one by one.

I've also added a `-W` option to the sphinx builders to convert any warnings into errors, in order to avoid these problems piling up in the future.

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2025-01-08 17:31 UTC, Andrewwango commented
@tachella 
> Set single backquotes...

Is this backward compatible with people still doing double backtick?

> Added to automatic typing

Is it still nice and clean when you have complex typing e.g. `x: Union[torch.Tensor, deepinv.utils.TensorList]`?
How about the [new notation from python 3.10](https://peps.python.org/pep-0604/) of `x: Tensor | TensorList`?

2025-01-09 08:54 UTC, tachella commented
> @tachella
> 
> > Set single backquotes...
> 
> Is this backward compatible with people still doing double backtick?

Yes, both will work

> 
> > Added to automatic typing
> 
> Is it still nice and clean when you have complex typing e.g. `x: Union[torch.Tensor, deepinv.utils.TensorList]`? How about the [new notation from python 3.10](https://peps.python.org/pep-0604/) of `x: Tensor | TensorList`?

Yes, both work, with the same flaws as stated above (ie only showing `Tensor` and not `torch.Tensor`

2025-01-10 13:51 UTC, Andrewwango commented on deepinv/datasets/fastmri.py
> +    :param Callable sample_filter: (optional) A callable object that takes a
I still don't fully understand what you mean by the links not working. For example I have just regenerated your docs - is this the intended output? E.g. Union and Callable aren't linked.
![image](https://github.com/user-attachments/assets/98f9aa29-5d05-47d5-a849-6f7e840a66d1)

2025-01-10 14:11 UTC, tachella commented on deepinv/datasets/fastmri.py
> +    :param Callable sample_filter: (optional) A callable object that takes a
so `Union` is not generally shown as a link, and `Callable` is the only other example that doesn't show a link without flagging an error (not sure why).

2025-01-10 22:13 UTC, Andrewwango commented on deepinv/loss/adversarial/base.py
> +        :return: (class:`torch.Tensor`) discriminator adversarial loss
```suggestion
        :return: (:class:`torch.Tensor`) discriminator adversarial loss
```

2025-01-10 22:17 UTC, Andrewwango commented on deepinv/training/trainer.py
> +        :param progress_bar: tqdm progress bar.
note that here, no type appears in the docs anymore for progress bar

2025-01-10 22:19 UTC, Andrewwango commented on deepinv/loss/measplit.py
> +    def adapt_model(self, model: torch.nn.Module, eval_n_samples=None):
Why remove the return typing for this method?

2025-01-10 22:24 UTC, Andrewwango commented on deepinv/loss/measplit.py
> +    class SplittingModel(Reconstructor):
what's the purpose of including SplittingModel inside SplittingLoss?

2025-01-11 13:53 UTC, tachella commented on deepinv/loss/measplit.py
> +    class SplittingModel(Reconstructor):
To have it appearing in the docs, before it was not the case.

2025-01-14 22:55 UTC, Andrewwango requested changes
Thanks for the hard work, please see comments above.

2025-01-17 12:53 UTC, tachella commented on deepinv/loss/measplit.py
> +    def adapt_model(self, model: torch.nn.Module, eval_n_samples=None):
you are right, I undid the changes

2025-01-17 12:53 UTC, tachella commented on deepinv/loss/adversarial/base.py
> +        :return: (class:`torch.Tensor`) discriminator adversarial loss
fixed

2025-01-20 06:43 UTC, merged