Generalized R2R Loss
deepinv/deepinv pull request #380
Opened 2024-12-27 19:45 UTC by bemc22

* Add the Generalized R2R loss (GR2R) for unsupervised denoising
* Add docs for GR2R loss
* Add test for GR2R loss 
* Add examples for GR2R loss
* Delete R2R loss since its a special case of GR2R

TODO

- [x] GR2R loss for gaussian, poisson and gamma distributions
- [x] GR2R tests
- [ ] GR2R docs
- [ ] deleted R2R loss
- [ ] examples for GR2R

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

2025-01-03 11:51 UTC, tachella requested changes
thanks for the PR!

I have mostly some documentation comments that could be improved.

My other concern is regarding the example: should we add a pretrained checkpoint to show good results with a single training epoch?

2025-01-03 11:51 UTC, tachella commented on deepinv/loss/r2r.py
> +
```suggestion
which includes the popular Gaussian, Poisson and Gamma noise distributions.
```

2025-01-03 11:51 UTC, tachella commented on deepinv/loss/r2r.py
> +    This loss generalizes the Recorrupted-to-Recorrupted (R2R) loss for the natural exponential family of noise models
It is not very clear what is the first R2R paper and what is the GR2R one. I would do something like


is 

The loss was first introduced in the `Recorrupted2Recorrupted paper <https://ieeexplore.ieee.org/document/9577798>`_ for the specific case of Gaussian noise, formalizing the `Noise2Noisier loss <https://arxiv.org/abs/1910.11908>`_ such that it is statistically equivalent to the supervised loss function defined on noisy/clean image pairs. The loss was later extended to other exponential family noise distributions in `Generalized Recorrupted2Recorrupted <https://arxiv.org/abs/2412.04648>`_, including Poisson, Gamma and Binomial noise distributions.

2025-01-03 11:51 UTC, tachella commented on deepinv/loss/r2r.py
> +        The ``sigma`` paramater is deprecated and will be removed in future versions. Use ``noise_model`` parameter instead.
```suggestion
        The ``sigma`` paramater is deprecated and will be removed in future versions. Use ``noise_model=deepinv.physics.GaussianNoise(sigma=sigma)`` instead.
```

2025-01-03 11:51 UTC, tachella commented on deepinv/loss/r2r.py
> +            print(
add at the beginning from `warnings import warn`
```suggestion
            warnings.warn( ...)
```
instead of the print

2025-01-03 11:51 UTC, tachella commented on deepinv/loss/r2r.py
> +        :param NoiseModel noise_model: Noise model of the natural exponential family.
```suggestion
        :param NoiseModel noise_model: Noise model of the natural exponential family. Implemented options are :class:`deepinv.physics.GaussianNoise`, :class:`deepinv.physics.PoissonNoise` and :class:`deepinv.physics.GammaNoise` 
```

2025-01-03 11:51 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +i.e., using noisy images only via the GR2R loss, which exploits knowledge about the noise distribution.
```suggestion
i.e., using noisy images only via the `Generalized Recorrupted2Recorrupted (GR2R) loss <https://arxiv.org/abs/2412.04648>`_, which exploits knowledge about the noise distribution.
```

2025-01-03 11:51 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +epochs = 1  # choose training epochs
is this giving reasonable results? we should probably update a checkpoint as in the other SURE example.

2025-01-03 11:52 UTC, tachella commented on deepinv/loss/r2r.py
> +
See https://en.wikipedia.org/wiki/Exponential_family for more details on the exponential family.

2025-01-03 21:29 UTC, bemc22 commented on deepinv/loss/r2r.py
> +    This loss generalizes the Recorrupted-to-Recorrupted (R2R) loss for the natural exponential family of noise models
thanks, update in [79f1cc3]

2025-01-03 21:29 UTC, bemc22 commented on deepinv/loss/r2r.py
> +        The ``sigma`` paramater is deprecated and will be removed in future versions. Use ``noise_model`` parameter instead.
thanks, update in [79f1cc3]

2025-01-03 21:29 UTC, bemc22 commented on deepinv/loss/r2r.py
> +            print(
thanks, update in [79f1cc3]

2025-01-03 21:29 UTC, bemc22 commented on deepinv/loss/r2r.py
> +        :param NoiseModel noise_model: Noise model of the natural exponential family.
thanks, update in [79f1cc3]

2025-01-03 21:29 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +i.e., using noisy images only via the GR2R loss, which exploits knowledge about the noise distribution.
thanks, update in [79f1cc3]

2025-01-03 21:52 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +i.e., using noisy images only via the GR2R loss, which exploits knowledge about the noise distribution.
thanks, updated in [9415d9b]

2025-01-03 21:55 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +epochs = 1  # choose training epochs
Okey, I have opened a PR in the [deepinv/demo](https://huggingface.co/deepinv/demo/discussions) on Hugging Face, where I uploaded the demo weights for the GR2R Poisson experiment. If accepted, lines 138-146 can be uncommented.

2025-01-04 11:07 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +predefined_noise_models = dict(
maybe predefine them already with noise levels?

2025-01-04 11:07 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +# We generate a dataset of noisy images corrupted by Poisson noise.
explain that the user can change the noise distribution

2025-01-04 11:09 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +
maybe say here that the user can change across different noise distributions?

2025-01-04 12:31 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +predefined_noise_models = dict(
thanks, updated in [adc00c9]

2025-01-04 12:31 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +# We generate a dataset of noisy images corrupted by Poisson noise.
thanks, updated in [adc00c9]

2025-01-04 12:31 UTC, bemc22 commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +
thanks, updated in [adc00c9]

2025-01-04 14:30 UTC, tachella commented on examples/self-supervised-learning/demo_r2r_denoising.py
> +epochs = 1  # choose training epochs
merged the hf PR

2025-01-04 16:20 UTC, tachella approved these changes

2025-01-04 16:20 UTC, merged