Docstring + minor updates
deepinv/deepinv pull request #51
Opened 2023-06-28 15:26 UTC by samuro95

In this PR
- update docstrings of several functions and example files.
- enable the plotting of the metrics in the Unfodled case: see examples/demo_vanilla_unfolded.py
- Add the "drunet" dataset for training on a large dataset.
- Debug Deep Equilibrium 

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [ ] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.md](../../CHANGELOG.md) (as applicable) (to come).

2023-06-28 18:45 UTC, matthieutrs approved these changes

2023-06-29 06:49 UTC, tachella requested changes
great PR! There's just a bunch of typos in the docs that I'll fix myself

2023-06-29 06:49 UTC, tachella commented on deepinv/optim/fixed_point.py
> +        :return tuple: `(x,metrics)` with `x` the fixed-point solution and
missing double ``

2023-06-29 06:49 UTC, tachella commented on deepinv/unfolded/deep_equilibrium.py
> +    See `<http://implicit-layers-tutorial.org/deep_equilibrium_models/>` for more details.
an _ is missing after the link

2023-06-29 06:49 UTC, tachella commented on deepinv/unfolded/deep_equilibrium.py
> +    \label{eq:fixed_point}
Is this well indented?

2023-06-29 06:49 UTC, tachella commented on deepinv/unfolded/deep_equilibrium.py
> +        :return: If `compute_metrics` is False,  returns (torch.Tensor) the output of the algorithm.
double `` missing

2023-06-29 06:49 UTC, tachella commented on examples/unfolded/demo_DEQ.py
> +For vializing the training, you can use Weight&Bias (wandb) by setting `wandb_vis=True`.
"visualizing" also double `` are missing in wandb_vis

2023-06-29 06:49 UTC, tachella commented on examples/unfolded/demo_vanilla_unfolded.py
> +For vializing the training, you can use Weight&Bias (wandb) by setting `wandb_vis=True`.
same as before "visualizing" and double ``

2023-06-29 08:00 UTC, merged